class Autogenerated {
  String? province;
  String? district;
  String? commune;
  String? street;
  String? numberHouse;
  String? phoneNumber;
  int? customerId;

  Autogenerated({
    this.province,
    this.district,
    this.commune,
    this.street,
    this.numberHouse,
    this.phoneNumber,
    this.customerId,
  });

  Autogenerated.fromJson(Map<String, dynamic> json) {
    province = json['province'];
    district = json['district'];
    commune = json['commune'];
    street = json['street'];
    numberHouse = json['numberHouse'];
    phoneNumber = json['phoneNumber'];
    customerId = json['customerId'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['province'] = province;
    data['district'] = district;
    data['commune'] = commune;
    data['street'] = street;
    data['numberHouse'] = numberHouse;
    data['phoneNumber'] = phoneNumber;
    data['customerId'] = customerId;
    return data;
  }
}
